@baseUrl = http://localhost:5080
@contentType = application/json

### old format
POST {{baseUrl}}/contracts/search
Content-Type: {{contentType}}

{
  "projection": [
    "id", "name", "description",
    "createdById", "createdBy", "createdAt",
    "updatedById", "updatedBy", "updatedAt",
    "customerDetailsSdiCode", "customerDetailsEmail",
    "customerDetailsFirstName", "customerDetailsLastName",
    "customerDetailsFiscalCode", "customerDetailsVatId", 
    "customerDetailsCompanyName", "brand", "customerDetailsPhone",
    "customerDetailsLandlinePhone", "customerDetailsCompanyFiscalCode"
  ],
  "sort": [
    { "field": "customerDetailsCompanyName", "direction": "Ascending" }
  ],
  "page": { "number": 8, "size": 20 }
}


### acq format
POST {{baseUrl}}/contracts/search
Content-Type: {{contentType}}

{
    "search": "maes",
    "status": [],
    "statusType": [],
    "organizations": [],
    "orgMembers": [],
    "products": [],
    "productOptions": [],
    "brands": [
      "75b1a5db-6828-4000-a4bb-caab2ea3234b",
      "72ec827d-eb83-44ed-acb5-76bd1f2832cf"
    ],
    "workProfiles": [],
    "assignees": [],
    "paid": [],
    "automationStatus": [],
    "signatureDate": {},
    "createdAtDate": {},
    "options": {
        "columns": [
          "code",
          "createdAt",
          "brand",
          "brandId",
          "customerDetailsFirstName", 
          "customerDetailsLastName"
        ],
        "page": 1,
        "pageSize": 100
    }
}