<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WeByte.Search.Api</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Search.Application\Search.Application.csproj" />
    <ProjectReference Include="..\Search.Core\Search.Core.csproj" />
    <ProjectReference Include="..\Search.Infrastructure.Sql\Search.Infrastructure.Sql.csproj" />
    <ProjectReference Include="..\Search.Infrastructure.Mongo\Search.Infrastructure.Mongo.csproj" />
    <ProjectReference Include="..\Search.Sql\Search.Sql.csproj" />
    <ProjectReference Include="..\Search.Export.Xlsx\Search.Export.Xlsx.csproj" />
  </ItemGroup>

</Project>
