@baseUrl = http://localhost:5080
@contentType = application/json

### Ricerca: price >= 10 AND tags ⊇ {sale|novità}, ordinati per prezzo desc
POST {{baseUrl}}/work-profiles/search
Content-Type: {{contentType}}

{
  "search": "aur",
  "filter": {
    "and": [
      { "field": "spaceId", "op": "eq", "value": "4ae7781f-28a9-4070-b545-dfeb854c8764" }
    ]
  },
  "projection": ["id", "name", "userNames", "userIds", "spaceId", "brandName"],
  "sort": [
    { "field": "brandName", "direction": "Ascending" }
  ],
  "page": { "number": 1, "size": 10 }
}